#!/bin/bash'          
#export PATH=.:\${PATH}
source /etc/profile
source /root/.bash_profile
cd /Apps/phpin

PHP_DEPEND="php70w \
            php70w-bcmath \
            php70w-cli \
            php70w-common \
            php70w-dba \
            php70w-devel \
            php70w-embedded \
            php70w-enchant \
            php70w-fpm \
            php70w-gd \
            php70w-imap \
            php70w-interbase \
            php70w-intl \
            php70w-ldap \
            php70w-mbstring \
            php70w-mcrypt \
            php70w-mysql \
            php70w-mysqlnd \
            php70w-odbc \
            php70w-opcache \
            php70w-pdo \
            php70w-pdo_dblib \
            php70w-pear \
            php70w-pecl-apcu \
            php70w-pecl-imagick \
            php70w-pecl-memcached \
            php70w-pecl-mongodb \
            php70w-pecl-redis \
            php70w-pecl-xdebug \
            php70w-pgsql \
            php70w-phpdbg \
            php70w-process \
            php70w-pspell \
            php70w-recode \
            php70w-snmp \
            php70w-soap \
            php70w-tidy \
            php70w-xml \
            php70w-xmlrpc"; 
echo ${PHP_DEPEND}
            #获取 并 安装php
rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm 
yum install --skip-broken -y ${PHP_DEPEND}
