version: '3'
services:

   # 定义三个服务nginx,php,mysql
  mysql:
    image: img-mysql:latest
    build:  
        context: .
        dockerfile: mysql-Dockerfile
#    ports:  
#      - "3306:3306"
    volumes:
      - /Apps/confs/sql/my.cnf:/etc/my.cnf
      - /Apps/share_datas/sql:/var/lib/mysql/
    restart: always
    # 设置MYSQL_ROOT_PASSWORD环境变量，这里是设置mysql的root密码。这里为root。
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: docker-entrypoint.sh mysqld
    container_name:
      mysql

  nginx-php-fpm:
    image:
      img-ngx-php:latest
    build:
      context: .
      dockerfile: ngx-php-Dockerfile
     
    # 依赖mysql服务，意味着在启动nginx之前先启动mysql
    depends_on:
      - mysql
    #链接数据库 命名db
    links:
      - mysql:db
    volumes:
      - /Apps/projects:/Apps
      - /Apps/logs/nginx:/var/log/nginx
      - /Apps/logs/php:/var/log/php
      - /Apps/confs/php/php-fpm.d.conf:/etc/php-fpm.d/www.conf:ro 
      - /Apps/confs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
      - /Apps/confs/nginx/conf.d.conf:/etc/nginx/conf.d/default.conf

    # nginx意外退出时自动重启
    restart: 
      always
 
    # 映射 暴露80 源80
    ports:
      - "80:80"
    #命令
    command: /usr/sbin/startNgxPhp.sh
    # 容器名称
    container_name: 
      nginx-php 
