FROM        centos
MAINTAINER        eastgreatwolf <eastgreatwolf@aliyun.com>
    #PHP_HOME

#修改 用户id 和 宿主机用户 id一致
ENV       NGINX_USER_ID 1000

ENV       PHP_HOME /usr/local/php
ENV       PHP_VERSION php-7.2.4
ENV       SRC_DIR /Apps/
WORKDIR ${SRC_DIR}
ENV       PATH=".:${PHP_HOME}/bin:${PATH}"
ENV       set -o vi
ENV       PHP_DEPEND    libxml2\ 
            libxml2-devel\ 
            openssl\ 
            openssl-devel\ 
            bzip2\ 
            bzip2-devel\ 
            libcurl\ 
            libcurl-devel\ 
            libjpeg\ 
            libjpeg-devel\ 
            libpng\ 
            libpng-devel\ 
            freetype\ 
            freetype-devel\ 
            gmp\ 
            gmp-devel\ 
            #        libmcrypt\ 
            #        libmcrypt-devel\ 
            readline\ 
            readline-devel\ 
            libxslt\ 
            libxslt-devel 
ENV     CONF_ARGS --prefix=${PHP_HOME} \ 
                  --with-config-file-path=/etc \ 
                  --enable-fpm \ 
                  --with-fpm-user=nginx \ 
                  --with-fpm-group=nginx \ 
                  --enable-inline-optimization \ 
                  --disable-debug \ 
                  --disable-rpath \ 
                  --enable-shared \ 
                  --enable-soap \ 
                  --with-libxml-dir \ 
                  --with-xmlrpc \ 
                  --with-openssl \ 
                  --with-mhash \ 
                  --with-pcre-regex \ 
                  --with-sqlite3 \ 
                  --with-zlib \ 
                  --enable-bcmath \ 
                  --with-iconv \ 
                  --with-bz2 \ 
                  --enable-calendar \ 
                  --with-curl \ 
                  --with-cdb \ 
                  --enable-dom \ 
                --enable-exif \ 
                  --enable-fileinfo \ 
                  --enable-filter \ 
                  --with-pcre-dir \ 
                --enable-ftp \ 
                  --with-gd \ 
                  --with-openssl-dir \ 
                  --with-jpeg-dir \ 
                  --with-png-dir \ 
                  --with-zlib-dir \ 
                  --with-freetype-dir  \ 
                  --enable-gd-jis-conv \ 
                  --with-gettext \ 
                  --with-gmp \ 
                  --with-mhash \ 
                  --enable-json \ 
                  --enable-mbstring \ 
                  --enable-mbregex \ 
                  --enable-mbregex-backtrack \ 
                  --with-libmbfl \ 
                  --with-onig \ 
                  --enable-pdo \ 
                  --with-mysqli=mysqlnd \ 
                  --with-pdo-mysql=mysqlnd \ 
                  --with-zlib-dir \ 
                  --with-pdo-sqlite \ 
                  --with-readline \ 
                  --enable-session \ 
                  --enable-shmop \ 
                  --enable-simplexml \ 
                  --enable-sockets \ 
                  --enable-sysvmsg \ 
                  --enable-sysvsem \ 
                  --enable-sysvshm \ 
                  --enable-wddx \ 
                  --with-libxml-dir \ 
                  --with-xsl \ 
                  --enable-zip \ 
                  --enable-mysqlnd-compression-support \ 
                  --with-pear \ 
                  --enable-opcache  
    #获取ngxinx rpm
RUN  useradd nginx -u ${NGINX_USER_ID} \  
    &&  rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm \
    &&  yum install -y nginx \  
#安装依赖
    &&  yum install -y ${PHP_DEPEND}\
    &&  yum install -y gcc \
    &&  gcc -v\
    &&  yum install -y wget \
#获取 并 安装php
    &&  wget http://cn2.php.net/get/${PHP_VERSION}.tar.gz/from/this/mirror -O ${PHP_VERSION}.tar.gz \
    &&  tar xzvf ${PHP_VERSION}.tar.gz \
    &&  cd ${PHP_VERSION} \
    &&  ./configure ${CONF_ARGS} \ 
    &&  make \
    &&  make install \
    &&  cp php.ini-production ${PHP_HOME}/etc/php.ini \
    &&  cp ${PHP_HOME}/etc/php-fpm.conf.default ${PHP_HOME}/etc/php-fpm.conf  \      
    &&  cp ${PHP_HOME}/etc/php-fpm.d/www.conf.default ${PHP_HOME}/etc/php-fpm.d/www.conf  \      
    &&  rm -fr ${SRC_DIR}${PHP_VERSION} ${SRC_DIR}${PHP_VERSION}.tar.gz \
    &&  cd  /usr/sbin \
    &&  echo '#!/bin/bash'                                     >startNgxPhp.sh \
    &&  echo "export PATH=${PHP_HOME}/bin:${PATH}"          >>startNgxPhp.sh \
    &&  echo "/usr/local/php/sbin/php-fpm"                    >>startNgxPhp.sh \
    &&  echo "/usr/sbin/nginx -g 'daemon off;'"               >>startNgxPhp.sh \
    &&  chmod +x startNgxPhp.sh  \
    &&  echo "USER_NAME=\`cat /etc/nginx/nginx.conf |grep ^user|awk '{printf \$2}'\`">>startNgxPhp.sh  \
    &&  echo "chown -R \${USER_NAME}:\${USER_NAME} /Apps"     >>startNgxPhp.sh \
    &&  pwd

CMD /usr/sbin/nginx -g 'daemon off;'

#    ENTRYPOINT /usr/sbin/nginx -g 'daemon off;'
#    ENTRYPOINT ["tail", "-f", "/dev/null"]

EXPOSE    80
